INFO:root:AddCommand
<<<<<<< HEAD
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "show cart" is Not Registered!
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/fiberhomeAN5006.py", line 553, in execute_command
    command_class = cls.command_factory.get_type(command)(params)
  File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type
    raise Exception('Resource Type "%s" is Not Registered!'%name)
Exception: Resource Type "show cart" is Not Registered!
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "showProfiles" is Not Registered!
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/fiberhomeAN5006.py", line 553, in execute_command
    command_class = cls.command_factory.get_type(command)(params)
  File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type
    raise Exception('Resource Type "%s" is Not Registered!'%name)
Exception: Resource Type "showProfiles" is Not Registered!
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "Show VLAN" is Not Registered!
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/fiberhomeAN5006.py", line 553, in execute_command
    command_class = cls.command_factory.get_type(command)(params)
  File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type
    raise Exception('Resource Type "%s" is Not Registered!'%name)
Exception: Resource Type "Show VLAN" is Not Registered!
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command | AttributeError: 'list' object has no attribute 'get'
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command
    task_result.get('result')
AttributeError: 'list' object has no attribute 'get'
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command | AttributeError: 'list' object has no attribute 'get'
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command
    task_result.get('result')
AttributeError: 'list' object has no attribute 'get'
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "showProfiles" is Not Registered!
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/fiberhomeAN3300.py", line 158, in execute_command
    command_class = cls.command_factory.get_type(command)(params)
  File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type
    raise Exception('Resource Type "%s" is Not Registered!'%name)
Exception: Resource Type "showProfiles" is Not Registered!
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "showProfiles" is Not Registered!
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/fiberhomeAN3300.py", line 158, in execute_command
    command_class = cls.command_factory.get_type(command)(params)
  File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type
    raise Exception('Resource Type "%s" is Not Registered!'%name)
Exception: Resource Type "showProfiles" is Not Registered!
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command | AttributeError: 'list' object has no attribute 'get'
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command
    task_result.get('result')
AttributeError: 'list' object has no attribute 'get'
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "show cart" is Not Registered!
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/fiberhomeAN5006.py", line 553, in execute_command
    command_class = cls.command_factory.get_type(command)(params)
  File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type
    raise Exception('Resource Type "%s" is Not Registered!'%name)
Exception: Resource Type "show cart" is Not Registered!
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command | AttributeError: 'list' object has no attribute 'get'
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command
    task_result.get('result')
AttributeError: 'list' object has no attribute 'get'
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command | AttributeError: 'list' object has no attribute 'get'
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command
    task_result.get('result')
AttributeError: 'list' object has no attribute 'get'
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command | AttributeError: 'list' object has no attribute 'get'
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command
    task_result.get('result')
AttributeError: 'list' object has no attribute 'get'
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command | AttributeError: 'str' object has no attribute 'get'
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command
    task_result.get('result')
AttributeError: 'str' object has no attribute 'get'
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
DEBUG:paramiko.transport:starting thread (client mode): 0x8865eb50
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.8.0
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2212, in _check_banner
ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 380, in readline
ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 609, in _read_timeout
ERROR:paramiko.transport:    raise EOFError()
ERROR:paramiko.transport:EOFError
ERROR:paramiko.transport:
ERROR:paramiko.transport:During handling of the above exception, another exception occurred:
ERROR:paramiko.transport:
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2039, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2217, in _check_banner
ERROR:paramiko.transport:    raise SSHException(
ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
DEBUG:paramiko.transport:starting thread (client mode): 0x886bce50
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.8.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] client mac:['hmac-sha1', 'hmac-sha1-96'] server mac:['hmac-sha1', 'hmac-sha1-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 172.18.10.66: b'356f7ca16f0e0a2a595ba772c891743d'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) failed.
DEBUG:paramiko.transport:EOF in transport thread
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 576, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 576, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 576, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 576, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 58, in run_command
    tn.read_until('Password:')
  File "/usr/lib/python3.8/telnetlib.py", line 304, in read_until
    i = self.cookedq.find(match)
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 576, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 95, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 97, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
=======
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
>>>>>>> 66cbb990f1b1c376e62f78f28747cf47bbec31cb
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
ERROR:jsonrpclib.SimpleJSONRPCServer:Server-side exception: <Fault -32603: Server error: File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command | IndexError: Replacement index 1 out of range for positional args tuple
>
Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 85, in run_command
    return {"result" : "add to valn {1} give error".format(self.__vlan_id), "port_indexes": self.__port_indexes}
IndexError: Replacement index 1 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 420, in _dispatch
    return func(*params)
  File "portman_core.py", line 153, in add_command
    return self.portman._execute_command(task, is_queue)
  File "/opt/portmanv3/portman_core2/portman.py", line 296, in _execute_command
    task_result = dslam_class.execute_command(
  File "/opt/portmanv3/portman_core2/vendors/zyxel.py", line 578, in execute_command
    return command_class.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 100, in run_command
    return self.run_command()
  File "/opt/portmanv3/portman_core2/vendors/zyxel_commands/add_to_vlan.py", line 102, in run_command
    print(("error : add to valn {1}".format(self.__vlan_id)))
IndexError: Replacement index 1 out of range for positional args tuple
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
INFO:root:AddCommand
