Not Found: /api/v1/dslamport/add-to-vlan/
Not Found: /api/v1/dslamport/add-to-vlan/
Unauthorized: /api/v1/dslamport/run-command/
Internal Server Error: /api/v1/dslamport/run-command/
Traceback (most recent call last):
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
Internal Server Error: /api/v1/dslamport/run-command/
Traceback (most recent call last):
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /favicon.ico
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/dashboard.css
Not Found: /static/admin/js/nav_sidebar.js
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/css/base.css
Internal Server Error: /api/v1/dslamport/run-command/
Traceback (most recent call last):
  File "/home/sajad/Project/portmanv3/portman_web/dslam/views.py", line 5970, in post
    PortmanLogging(result, log_params)
  File "/home/sajad/Project/portmanv3/portman_web/classes/portman_logging.py", line 10, in __init__
    self.save_to_db()
  File "/home/sajad/Project/portmanv3/portman_web/classes/portman_logging.py", line 20, in save_to_db
    return PortmanLog.objects.create(request=self.log_params['log_port_data'],
KeyError: 'log_port_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sajad/Project/portmanv3/portman_web/dslam/views.py", line 6015, in post
    PortmanLogging('', log_params)
  File "/home/sajad/Project/portmanv3/portman_web/classes/portman_logging.py", line 10, in __init__
    self.save_to_db()
  File "/home/sajad/Project/portmanv3/portman_web/classes/portman_logging.py", line 20, in save_to_db
    return PortmanLog.objects.create(request=self.log_params['log_port_data'],
KeyError: 'log_port_data'
Internal Server Error: /api/v1/dslamport/run-command/
Traceback (most recent call last):
  File "/home/sajad/Project/portmanv3/portman_web/dslam/views.py", line 5970, in post
    PortmanLogging(result, log_params)
  File "/home/sajad/Project/portmanv3/portman_web/classes/portman_logging.py", line 10, in __init__
    self.save_to_db()
  File "/home/sajad/Project/portmanv3/portman_web/classes/portman_logging.py", line 20, in save_to_db
    return PortmanLog.objects.create(request=self.log_params['log_port_data'],
KeyError: 'log_port_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sajad/Project/portmanv3/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sajad/Project/portmanv3/portman_web/dslam/views.py", line 6015, in post
    PortmanLogging('', log_params)
  File "/home/sajad/Project/portmanv3/portman_web/classes/portman_logging.py", line 10, in __init__
    self.save_to_db()
  File "/home/sajad/Project/portmanv3/portman_web/classes/portman_logging.py", line 20, in save_to_db
    return PortmanLog.objects.create(request=self.log_params['log_port_data'],
KeyError: 'log_port_data'
Not Found: /api/v1/dslamport/portman-log/
Not Found: /api/v1/dslamport/portman-log/
Unauthorized: /api/v1/portman-log/
Method Not Allowed: /api/v1/portman-log/
Not Found: /api/v1/portman-log/
