Unauthorized: /api/v1/port-command/
Unauthorized: /api/v1/dslam-port/385057/report/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam-port/385057/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/permission-profile/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/port-command/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam-port/385057/report/
Unauthorized: /api/v1/dslam-port/385057/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Not Found: /api/v1/users/permission-profile/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Internal Server Error: /api/v1/dslam/icmp/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1166, in post
    result = utility.run_icmp_command(dslam_id, icmp_type, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 61, in run_icmp_command
    return c.run_icmp_command(dslam_id, icmp_type, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Unauthorized: /api/v1/users/get_permission/
Internal Server Error: /api/v1/dslam/icmp/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1166, in post
    result = utility.run_icmp_command(dslam_id, icmp_type, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 61, in run_icmp_command
    return c.run_icmp_command(dslam_id, icmp_type, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Internal Server Error: /api/v1/dslam/icmp/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1166, in post
    result = utility.run_icmp_command(dslam_id, icmp_type, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 61, in run_icmp_command
    return c.run_icmp_command(dslam_id, icmp_type, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Internal Server Error: /api/v1/dslam/icmp/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1166, in post
    result = utility.run_icmp_command(dslam_id, icmp_type, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 61, in run_icmp_command
    return c.run_icmp_command(dslam_id, icmp_type, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Internal Server Error: /api/v1/dslamport/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1194, in post
    result = utility.dslam_port_run_command(dslam_obj.pk, command, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 21, in dslam_port_run_command
    return c.add_command(dslam_id, command, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Internal Server Error: /api/v1/dslamport/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1194, in post
    result = utility.dslam_port_run_command(dslam_obj.pk, command, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 21, in dslam_port_run_command
    return c.add_command(dslam_id, command, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Internal Server Error: /api/v1/dslamport/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1194, in post
    result = utility.dslam_port_run_command(dslam_obj.pk, command, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 21, in dslam_port_run_command
    return c.add_command(dslam_id, command, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/dslam/1396/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1396/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1396/board/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/1396/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/73/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/73/dslam_current_icmp_result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/73/board/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/73/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Internal Server Error: /api/v1/dslamport/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1194, in post
    result = utility.dslam_port_run_command(dslam_obj.pk, command, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 21, in dslam_port_run_command
    return c.add_command(dslam_id, command, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 696, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 1453, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "show port" is Not Registered!\n')
Internal Server Error: /api/v1/dslamport/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1194, in post
    result = utility.dslam_port_run_command(dslam_obj.pk, command, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 21, in dslam_port_run_command
    return c.add_command(dslam_id, command, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Internal Server Error: /api/v1/dslamport/command2/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
Internal Server Error: /api/v1/dslamport/command2/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
Not Found: /api/v1/users/permission-profile/
Not Found: /api/v1/users/permission-profile/
Not Found: /api/v1/users/permission-profile/
Forbidden: /api/v1/dslam/
Forbidden: /api/v1/dslam/
Forbidden: /api/v1/dslam/
Unauthorized: /api/v1/switch/
Not Found: /favicon.ico
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/dslamport/events/
Unauthorized: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/dslamport/events/
Not Found: /api/v1/users/permission-profile/
Not Found: /api/v1/users/permission-profile/
Unauthorized: /api/v1/users/permission-profile/
Not Found: /favicon.ico
<<<<<<< HEAD
Not Found: /api/v1/users/permission-profile/
Unauthorized: /api/v1/users/permission-profile/
Unauthorized: /api/v1/users/permission-profile/
Unauthorized: /api/v1/users/permission-profile/
Not Found: /api/v1/users/permission-profile/
Unauthorized: /api/v1/users/permission-profile/
Unauthorized: /api/v1/users/permission-profile/
Not Found: /api/v1/users/permission-profile/
Not Found: /api/v1/users/permission-profile/
Unauthorized: /api/v1/users/permission-profile/
=======
Unauthorized: /api/v1/router/router-runCommand/
Unauthorized: /api/v1/switch/connect_handler_test/
Internal Server Error: /users/get-token
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "5.202.129.160" and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework_jwt/views.py", line 57, in post
    if serializer.is_valid():
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework_jwt/serializers.py", line 50, in validate
    user = authenticate(**credentials)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/auth/backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "5.202.129.160" and accepting
	TCP/IP connections on port 5432?

>>>>>>> a89686efd6205ce22720dd21ff7d87a21206679b
Unauthorized: /api/v1/users/permission-profile/
Unauthorized: /api/v1/users/get_permission/
Not Found: /
Not Found: /favicon.ico
Internal Server Error: /admin/switch/switchcommand/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 814, in log_addition
    object_repr=str(object),
TypeError: __str__ returned non-string (type SwitchType)
Internal Server Error: /admin/switch/switchcommand/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 814, in log_addition
    object_repr=str(object),
TypeError: __str__ returned non-string (type SwitchType)
Internal Server Error: /admin/switch/switchcommand/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 814, in log_addition
    object_repr=str(object),
TypeError: __str__ returned non-string (type SwitchType)
Internal Server Error: /admin/switch/switchcommand/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 814, in log_addition
    object_repr=str(object),
TypeError: __str__ returned non-string (type SwitchType)
Internal Server Error: /admin/router/routercommand/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 814, in log_addition
    object_repr=str(object),
TypeError: __str__ returned non-string (type RouterType)
Internal Server Error: /admin/switch/switchcommand/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 814, in log_addition
    object_repr=str(object),
TypeError: __str__ returned non-string (type SwitchType)
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam-port/385057/report/
Unauthorized: /api/v1/port-command/
Unauthorized: /api/v1/dslam-port/385057/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/port-command/
Unauthorized: /api/v1/dslam-port/385057/report/
Unauthorized: /api/v1/dslam-port/385057/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/port-command/
Unauthorized: /api/v1/dslam-port/385057/report/
Unauthorized: /api/v1/dslam-port/385057/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Internal Server Error: /api/v1/dslam/icmp/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1166, in post
    result = utility.run_icmp_command(dslam_id, icmp_type, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 61, in run_icmp_command
    return c.run_icmp_command(dslam_id, icmp_type, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Not Found: /favicon.ico
Unauthorized: /api/v1/dslam/1391/dslamreport/
Unauthorized: /api/v1/dslam/1391/board/
Unauthorized: /api/v1/dslam/1391/dslam_current_icmp_result/
Unauthorized: /api/v1/dslam/command/result/
Unauthorized: /api/v1/command/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/get_fifty_five_precntage/
Unauthorized: /api/v1/dslam/1391/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
