<<<<<<< HEAD
=======
Method Not Allowed: /api/v1/province/get_provinces/
Internal Server Error: /api/v1/province/get_provinces/
Traceback (most recent call last):
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'django.db.models.query.QuerySet'>`
>>>>>>> 5f2bcea0c6772041ce3f7ff17ef1f302c4a99441
Unauthorized: /api/v1/province/get_provinces/
Internal Server Error: /api/v1/dslamport/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1200, in post
    result = utility.dslam_port_run_command(dslam_obj.pk, command, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 21, in dslam_port_run_command
    return c.add_command(dslam_id, command, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 696, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 1453, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "show cart" is Not Registered!\n')
Internal Server Error: /api/v1/dslamport/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1200, in post
    result = utility.dslam_port_run_command(dslam_obj.pk, command, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 21, in dslam_port_run_command
    return c.add_command(dslam_id, command, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 696, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 1453, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "showProfiles" is Not Registered!\n')
Internal Server Error: /api/v1/dslamport/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1200, in post
    result = utility.dslam_port_run_command(dslam_obj.pk, command, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 21, in dslam_port_run_command
    return c.add_command(dslam_id, command, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 696, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 1453, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/opt/portmanv3/portman_core2/vendors/command_factory.py", line 13, in get_type | Exception: Resource Type "Show VLAN" is Not Registered!\n')
Internal Server Error: /api/v1/dslamport/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1200, in post
    result = utility.dslam_port_run_command(dslam_obj.pk, command, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 21, in dslam_port_run_command
    return c.add_command(dslam_id, command, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 696, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 1453, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/opt/portmanv3/portman_core2/portman.py", line 414, in _execute_command | AttributeError: \'list\' object has no attribute \'get\'\n')
Unauthorized: /api/v1/reseller-port/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Not Found: /api/v1/contact/portmap/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
